// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZrriiXHTROalI1eugQgbHSJvTTUpH3iU',
    appId: '1:733423445740:web:8a474ff47cc8bf6953e7c9',
    messagingSenderId: '733423445740',
    projectId: 'raghunathamlucknow',
    authDomain: 'raghunathamlucknow.firebaseapp.com',
    storageBucket: 'raghunathamlucknow.firebasestorage.app',
    measurementId: 'G-W1VL33ZW8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcS-DGQXKz4lPwsG2F4LLc8xQ9gZyKG1U',
    appId: '1:733423445740:android:539497db1ce3e6f953e7c9',
    messagingSenderId: '733423445740',
    projectId: 'raghunathamlucknow',
    storageBucket: 'raghunathamlucknow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7xSIZ97vxIAhQEBcWkR4HXSRbA_H3raA',
    appId: '1:733423445740:ios:a4e13cf8ce8c2cd353e7c9',
    messagingSenderId: '733423445740',
    projectId: 'raghunathamlucknow',
    storageBucket: 'raghunathamlucknow.firebasestorage.app',
    iosBundleId: 'com.raghunathamlucknow.raghunathamhomes',
  );
}
